import { useRouter } from 'next/router';
import React from 'react'
import { data } from'@/data'
import Head from 'next/head';

const SinglePage = () => {
    const router = useRouter()
    const singleId = router.query;
    const findById = data.find((el) => {
        return el?.id == +singleId.id;
    })
  return (
    <>
      <Head>
        <title>{findById?.name} | {findById?.id}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     
      <div className="ggg">
      <h1>{findById?.name}</h1>
       <h2>{findById?.title}</h2>
       <b>{findById?.id}</b>
      </div>
     
    </>
  )
}

export default SinglePage