import { pizzas } from '@/pizza';
import Head from 'next/head'
import Image from 'next/image';
import { useRouter } from 'next/router';
import React from 'react'

const SinglePizza = () => {
    const router = useRouter()
    const singleId = router.query;
    const findById = pizzas.find((el) => {
        return el?.id == +singleId.id;
    })

  return (
    <>
    <Head>
        <title>{findById?.name} | {findById?.id}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


              
              <div className="card2">
              <Image fill src={findById?.img} alt="" />
              <h2>{findById?.name}</h2>
              <p>{findById?.desc}</p>
              <button>{findById?.narxi}so'mdan</button>
              </div>
              
    </>
  )
}

export default SinglePizza