import Head from "next/head";
import React from "react";
import { data } from "@/data";
import Link from "next/link";

const Blog = () => {
  console.log(data);
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="parent">
          {data?.map((el) => (
              <Link href={`/blog/${el?.id}`} key={el?.id} className="card"  >
              <h1>{el?.name}</h1>
              <p>{el?.title}</p>
              </Link>
            
          ))}
        </div>
      </div>
    </>
  );
};

export default Blog;
