import Head from 'next/head'
import s from "../styles/home.module.css"


export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <div className="ab">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente <br />
        repellendus non aliquam et dolor cupiditate dolorem officia assumenda <br />
        corporis. Nam adipisci illo tempora corrupti sint. Ipsa laborum <br />
        inventore, adipisci non dolorem, facere amet iusto omnis mollitia fuga, <br />
        temporibus distinctio repudiandae aspernatur ea pariatur quas! Eligendi, <br />
        nihil quia. Voluptate, sit dolore. Itaque rem est reiciendis dolores <br />
        vero corporis vitae repellendus. Nemo eos fugit sapiente itaque <br />
        reprehenderit error, ducimus dolorem deleniti vitae! Animi voluptas quas <br />
        quisquam impedit! Dolorem ducimus harum nisi vitae voluptas ad vero. <br />
        Iusto, libero exercitationem earum quis pariatur voluptate harum <br />
        perferendis, neque quia corrupti qui architecto! Magnam, consectetur <br />
        illo.
      </p>
      </div>
      
    </>
  )
}
