import { pizzas } from '@/pizza'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'

const Pizza = () => {
  return (
    <>
     <Head>
        <title>pizza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className="parent1">
          {pizzas?.map((el) => (
              <Link href={`/pizza/${el?.id}`} key={el?.id} className="card1"  >
              <Image fill src={el.img} alt="" />
              <h2>{el?.name}</h2>
              <p>{el?.desc}</p>
              <button>{el?.narxi}so'mdan</button>
              </Link>
            
          ))}
        </div>
      </div>

    </>
  )
}

export default Pizza